[core]

markdown.file_extensions = ["md", "markdown"]
text_sync = "full"
title_from_heading = true
incremental_references = false
paranoid = false

[code_action]
toc.enable = true
create_missing_file.enable = false

[completion]
candidates = 50
wiki.style = "file-path-stem"
